name: Go CI

on:
  push:
    branches:
      - main
      - renovate/**
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
  pull_request:
    branches:
      - main

jobs:

  strongo_workflow:
    permissions:
      contents: write
    uses: strongo/go-ci-action/.github/workflows/workflow.yml@main

    secrets:
      # Why 2 GitHub tokens? Consider to use only one token or document why we need 2
      gh_token: ${{ secrets.GITHUB_TOKEN }}

      # This token is used to retrieve private repositories
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    with:
      disable-version-bumping: false
